using System;
using System.Collections.Generic;

namespace StormUnarchiver.Services;

public class LanguageInfo
{
    public string Code { get; set; } = "";
    public string Name { get; set; } = "";
    public string NativeName { get; set; } = "";
    public string Flag { get; set; } = "";
}

public class LocalizationManager
{
    private static LocalizationManager? _instance;
    public static LocalizationManager Instance => _instance ??= new LocalizationManager();

    public event EventHandler? LanguageChanged;

    public string CurrentLanguage { get; private set; } = "ru";

    public static readonly LanguageInfo[] SupportedLanguages =
    [
        new() { Code = "ru", Name = "Русский", NativeName = "Русский", Flag = "🇷🇺" },
        new() { Code = "en", Name = "English", NativeName = "English", Flag = "🇬🇧" },
        new() { Code = "de", Name = "Deutsch", NativeName = "Deutsch", Flag = "🇩🇪" },
        new() { Code = "fr", Name = "Français", NativeName = "Français", Flag = "🇫🇷" },
        new() { Code = "zh", Name = "Chinese", NativeName = "简体中文", Flag = "🇨🇳" },
        new() { Code = "ja", Name = "Japanese", NativeName = "日本語", Flag = "🇯🇵" }
    ];

    private readonly Dictionary<string, Dictionary<string, string>> _strings = new()
    {
        ["ru"] = new()
        {
            ["AppTitle"] = "STORM UNARCHIVER 1.0.0",
            ["WatchedFolders"] = "Папки для отслеживания",
            ["PairsCount"] = "{0} пар",
            ["AddPair"] = "Добавить пару",
            ["WatchFolderTooltip"] = "Папка-источник (откуда отслеживать архивы)",
            ["OutputFolderTooltip"] = "Папка назначения (куда распаковывать)",
            ["BrowseSourceTooltip"] = "Выбрать папку-источник через проводник",
            ["BrowseOutputTooltip"] = "Выбрать папку назначения через проводник",
            ["OpenSourceTooltip"] = "Открыть папку-источник в Проводнике Windows",
            ["OpenOutputTooltip"] = "Открыть папку назначения в Проводнике Windows",
            ["RemovePairTooltip"] = "Удалить эту пару папок",
            ["DragWatchPrompt"] = "Перетащите папку сюда или нажмите кнопку выбора",
            ["DragOutputPrompt"] = "Перетащите папку назначения сюда",
            ["EmptyPairsTitle"] = "Нет добавленных пар папок",
            ["EmptyPairsSubtitle"] = "Нажмите «Добавить пару», чтобы задать источник архивов и папку распаковки.",
            ["EmptyPairsButton"] = "Добавить первую пару",
            ["StartMonitoring"] = "Начать мониторинг",
            ["StopMonitoring"] = "Остановить мониторинг",
            ["Processed"] = "Распаковано",
            ["Errors"] = "Ошибки",
            ["DeleteArchive"] = "Удалять архив",
            ["DeleteArchiveTooltip"] = "Удалять исходный архив после успешной распаковки",
            ["RecursiveUnpack"] = "Вложенные",
            ["RecursiveUnpackTooltip"] = "Рекурсивная распаковка: автоматически распаковывать вложенные архивы",
            ["LowPriority"] = "Эко-режим",
            ["LowPriorityTooltip"] = "Эко-режим: фоновый низкий приоритет CPU и диска",
            ["AutoStart"] = "Автозапуск",
            ["AutoStartTooltip"] = "Запускать STORM UNARCHIVER при старте Windows",
            ["Subfolders"] = "Подпапки",
            ["SubfoldersTooltip"] = "Отслеживать архивы во всех подпапках директории",
            ["PreserveStructure"] = "Структура",
            ["PreserveStructureTooltip"] = "Сохранять структуру каталогов внутри архива",
            ["Notifications"] = "Уведомления",
            ["NotificationsTooltip"] = "Показывать всплывающие уведомления Windows",
            ["FilterPresets"] = "Пресеты фильтров:",
            ["PresetAll"] = "Все форматы (100+)",
            ["PresetCommon"] = "Основные (ZIP, RAR, 7Z, TAR)",
            ["PresetDiskImages"] = "Образы дисков (ISO, IMG, VHD)",
            ["PresetReset"] = "Сбросить",
            ["OnlyFormats"] = "Только",
            ["ExcludeFormats"] = "Исключить",
            ["Password"] = "Пароль",
            ["PasswordPlaceholder"] = "для архивов",
            ["RevealPasswordTooltip"] = "Показать или скрыть пароль",
            ["PasswordDictTooltip"] = "Менеджер словарей паролей (автоматический подбор)",
            ["PasswordDictTitle"] = "Словарь паролей",
            ["PasswordDictSubtitle"] = "Автоподбор для защищенных архивов",
            ["PasswordDictDesc"] = "Введите список паролей (по одному в строке). При распаковке зашифрованных архивов STORM автоматически переберет их:",
            ["PasswordDictPick"] = "Выбрать .txt файл",
            ["PasswordDictClear"] = "Очистить",
            ["Delay"] = "Задержка",
            ["DelaySec"] = "{0} сек",
            ["Threads"] = "Потоки",
            ["Retries"] = "Повторы",
            ["ActivityLog"] = "Журнал активности",
            ["LogFilterAll"] = "Все",
            ["LogFilterSuccess"] = "Успешно",
            ["LogFilterError"] = "Ошибки",
            ["LogFilterInfo"] = "Инфо",
            ["LogSearchPlaceholder"] = "Поиск в журнале...",
            ["Export"] = "Экспорт",
            ["ExportTooltip"] = "Экспортировать журнал в TXT или CSV файл",
            ["ClearLog"] = "Очистить",
            ["ClearLogTooltip"] = "Очистить все записи журнала",
            ["EmptyLogTitle"] = "Журнал активности пуст",
            ["EmptyLogSubtitle"] = "События мониторинга и распаковки будут отображаться здесь в реальном времени.",
            ["StatusReady"] = "Готов к мониторингу",
            ["StatusMonitoring"] = "Мониторинг активен ({0} пар)",
            ["StatusStopped"] = "Мониторинг остановлен",
            ["AboutTooltip"] = "О программе и справка",
            ["AboutDescription"] = "Автоматическая фоновая распаковка архивов (100+ форматов) в реальном времени, словари паролей, рекурсивная распаковка и эко-режим.",
            ["SupportedFormats"] = "Поддержка форматов:",
            ["GoToGitHub"] = "Перейти на GitHub",
            ["ThemeSelectorTooltip"] = "Выбрать тему оформления",
            ["LanguageSelectorTooltip"] = "Выбрать язык интерфейса",
            ["SingleInstanceTitle"] = "STORM UNARCHIVER",
            ["SingleInstanceMsg"] = "Экземпляр программы уже запущен и выведен на передний план.",
            ["TrayOpen"] = "Открыть главное окно",
            ["TrayToggle"] = "Мониторинг",
            ["TrayExit"] = "Выход",
            ["TrayIdleStatus"] = "STORM UNARCHIVER 1.0.0 — Ожидание",
            ["TrayActiveStatus"] = "STORM UNARCHIVER 1.0.0 — Мониторинг активен"
        },
        ["en"] = new()
        {
            ["AppTitle"] = "STORM UNARCHIVER 1.0.0",
            ["WatchedFolders"] = "Watched folders",
            ["PairsCount"] = "{0} pairs",
            ["AddPair"] = "Add pair",
            ["WatchFolderTooltip"] = "Source folder (watch for incoming archives)",
            ["OutputFolderTooltip"] = "Destination folder (where to extract)",
            ["BrowseSourceTooltip"] = "Browse source folder in Windows Explorer",
            ["BrowseOutputTooltip"] = "Browse destination folder in Windows Explorer",
            ["OpenSourceTooltip"] = "Open source folder in Windows Explorer",
            ["OpenOutputTooltip"] = "Open destination folder in Windows Explorer",
            ["RemovePairTooltip"] = "Remove this folder pair",
            ["DragWatchPrompt"] = "Drag folder here or click browse button",
            ["DragOutputPrompt"] = "Drag destination folder here",
            ["EmptyPairsTitle"] = "No folder pairs added",
            ["EmptyPairsSubtitle"] = "Click 'Add pair' to set up source and extraction folders.",
            ["EmptyPairsButton"] = "Add first pair",
            ["StartMonitoring"] = "Start monitoring",
            ["StopMonitoring"] = "Stop monitoring",
            ["Processed"] = "Extracted",
            ["Errors"] = "Errors",
            ["DeleteArchive"] = "Delete archive",
            ["DeleteArchiveTooltip"] = "Delete source archive after successful extraction",
            ["RecursiveUnpack"] = "Nested",
            ["RecursiveUnpackTooltip"] = "Recursive unpack: automatically extract nested archives",
            ["LowPriority"] = "Eco mode",
            ["LowPriorityTooltip"] = "Eco mode: low CPU and disk I/O priority",
            ["AutoStart"] = "Autostart",
            ["AutoStartTooltip"] = "Launch STORM UNARCHIVER when Windows starts",
            ["Subfolders"] = "Subfolders",
            ["SubfoldersTooltip"] = "Watch archives across all subdirectories",
            ["PreserveStructure"] = "Structure",
            ["PreserveStructureTooltip"] = "Preserve folder structure inside archive",
            ["Notifications"] = "Notifications",
            ["NotificationsTooltip"] = "Show Windows toast notifications",
            ["FilterPresets"] = "Filter presets:",
            ["PresetAll"] = "All formats (100+)",
            ["PresetCommon"] = "Common (ZIP, RAR, 7Z, TAR)",
            ["PresetDiskImages"] = "Disk images (ISO, IMG, VHD)",
            ["PresetReset"] = "Reset",
            ["OnlyFormats"] = "Only",
            ["ExcludeFormats"] = "Exclude",
            ["Password"] = "Password",
            ["PasswordPlaceholder"] = "for archives",
            ["RevealPasswordTooltip"] = "Show or hide password",
            ["PasswordDictTooltip"] = "Password dictionary manager (sequential fallback)",
            ["PasswordDictTitle"] = "Password dictionary",
            ["PasswordDictSubtitle"] = "Sequential fallback for encrypted archives",
            ["PasswordDictDesc"] = "Enter passwords (one per line). STORM will try them sequentially on encrypted archives:",
            ["PasswordDictPick"] = "Pick .txt file",
            ["PasswordDictClear"] = "Clear",
            ["Delay"] = "Delay",
            ["DelaySec"] = "{0} sec",
            ["Threads"] = "Threads",
            ["Retries"] = "Retries",
            ["ActivityLog"] = "Activity log",
            ["LogFilterAll"] = "All",
            ["LogFilterSuccess"] = "Success",
            ["LogFilterError"] = "Errors",
            ["LogFilterInfo"] = "Info",
            ["LogSearchPlaceholder"] = "Search in log...",
            ["Export"] = "Export",
            ["ExportTooltip"] = "Export activity log to TXT or CSV file",
            ["ClearLog"] = "Clear",
            ["ClearLogTooltip"] = "Clear all log entries",
            ["EmptyLogTitle"] = "Activity log is empty",
            ["EmptyLogSubtitle"] = "Monitoring and extraction events will appear here in real time.",
            ["StatusReady"] = "Ready to monitor",
            ["StatusMonitoring"] = "Monitoring active ({0} pairs)",
            ["StatusStopped"] = "Monitoring stopped",
            ["AboutTooltip"] = "About and help",
            ["AboutDescription"] = "Automated real-time background archive extraction (100+ formats), password dictionary fallback, recursive unpacking, and eco mode.",
            ["SupportedFormats"] = "Supported formats:",
            ["GoToGitHub"] = "Go to GitHub",
            ["ThemeSelectorTooltip"] = "Select visual theme",
            ["LanguageSelectorTooltip"] = "Select interface language",
            ["SingleInstanceTitle"] = "STORM UNARCHIVER",
            ["SingleInstanceMsg"] = "An instance of the program is already running and has been brought to the foreground.",
            ["TrayOpen"] = "Open main window",
            ["TrayToggle"] = "Monitoring",
            ["TrayExit"] = "Exit",
            ["TrayIdleStatus"] = "STORM UNARCHIVER 1.0.0 — Idle",
            ["TrayActiveStatus"] = "STORM UNARCHIVER 1.0.0 — Monitoring active"
        },
        ["de"] = new()
        {
            ["AppTitle"] = "STORM UNARCHIVER 1.0.0",
            ["WatchedFolders"] = "Überwachte Ordner",
            ["PairsCount"] = "{0} Paare",
            ["AddPair"] = "Paar hinzufügen",
            ["WatchFolderTooltip"] = "Quellordner (auf neue Archive überwachen)",
            ["OutputFolderTooltip"] = "Zielordner (wohin entpackt wird)",
            ["BrowseSourceTooltip"] = "Quellordner im Windows Explorer durchsuchen",
            ["BrowseOutputTooltip"] = "Zielordner im Windows Explorer durchsuchen",
            ["OpenSourceTooltip"] = "Quellordner im Windows Explorer öffnen",
            ["OpenOutputTooltip"] = "Zielordner im Windows Explorer öffnen",
            ["RemovePairTooltip"] = "Dieses Ordnerpaar entfernen",
            ["DragWatchPrompt"] = "Ordner hierher ziehen oder Auswählen klicken",
            ["DragOutputPrompt"] = "Zielordner hierher ziehen",
            ["EmptyPairsTitle"] = "Keine Ordnerpaare hinzugefügt",
            ["EmptyPairsSubtitle"] = "Klicken Sie auf 'Paar hinzufügen', um Quell- und Zielordner einzurichten.",
            ["EmptyPairsButton"] = "Erstes Paar hinzufügen",
            ["StartMonitoring"] = "Überwachung starten",
            ["StopMonitoring"] = "Überwachung stoppen",
            ["Processed"] = "Entpackt",
            ["Errors"] = "Fehler",
            ["DeleteArchive"] = "Archiv löschen",
            ["DeleteArchiveTooltip"] = "Quelldatei nach erfolgreichem Entpacken löschen",
            ["RecursiveUnpack"] = "Verschachtelt",
            ["RecursiveUnpackTooltip"] = "Rekursives Entpacken verschachtelter Archive",
            ["LowPriority"] = "Öko-Modus",
            ["LowPriorityTooltip"] = "Öko-Modus: niedrige CPU- und Festplattenpriorität",
            ["AutoStart"] = "Autostart",
            ["AutoStartTooltip"] = "STORM UNARCHIVER beim Windows-Start ausführen",
            ["Subfolders"] = "Unterordner",
            ["SubfoldersTooltip"] = "Archive in allen Unterordnern überwachen",
            ["PreserveStructure"] = "Struktur",
            ["PreserveStructureTooltip"] = "Ordnerstruktur im Archiv beibehalten",
            ["Notifications"] = "Benachrichtigungen",
            ["NotificationsTooltip"] = "Windows-Toast-Benachrichtigungen anzeigen",
            ["FilterPresets"] = "Filter-Voreinstellungen:",
            ["PresetAll"] = "Alle Formate (100+)",
            ["PresetCommon"] = "Hauptformate (ZIP, RAR, 7Z, TAR)",
            ["PresetDiskImages"] = "Datenträgerabbilder (ISO, IMG, VHD)",
            ["PresetReset"] = "Zurücksetzen",
            ["OnlyFormats"] = "Nur",
            ["ExcludeFormats"] = "Ausschließen",
            ["Password"] = "Passwort",
            ["PasswordPlaceholder"] = "für Archive",
            ["RevealPasswordTooltip"] = "Passwort einblenden oder ausblenden",
            ["PasswordDictTooltip"] = "Passwort-Wörterbuch-Manager",
            ["PasswordDictTitle"] = "Passwort-Wörterbuch",
            ["PasswordDictSubtitle"] = "Automatische Passwortprüfung für verschlüsselte Archive",
            ["PasswordDictDesc"] = "Passwörter eingeben (eines pro Zeile):",
            ["PasswordDictPick"] = ".txt Datei wählen",
            ["PasswordDictClear"] = "Leeren",
            ["Delay"] = "Verzögerung",
            ["DelaySec"] = "{0} Sek",
            ["Threads"] = "Threads",
            ["Retries"] = "Wiederholungen",
            ["ActivityLog"] = "Aktivitätsprotokoll",
            ["LogFilterAll"] = "Alle",
            ["LogFilterSuccess"] = "Erfolgreich",
            ["LogFilterError"] = "Fehler",
            ["LogFilterInfo"] = "Info",
            ["LogSearchPlaceholder"] = "Im Protokoll suchen...",
            ["Export"] = "Exportieren",
            ["ExportTooltip"] = "Protokoll als TXT oder CSV exportieren",
            ["ClearLog"] = "Leeren",
            ["ClearLogTooltip"] = "Alle Protokolleinträge löschen",
            ["EmptyLogTitle"] = "Aktivitätsprotokoll ist leer",
            ["EmptyLogSubtitle"] = "Überwachungs- und Entpackereignisse werden hier live angezeigt.",
            ["StatusReady"] = "Bereit zur Überwachung",
            ["StatusMonitoring"] = "Überwachung aktiv ({0} Paare)",
            ["StatusStopped"] = "Überwachung gestoppt",
            ["AboutTooltip"] = "Über das Programm und Hilfe",
            ["AboutDescription"] = "Automatische Hintergrund-Entpackung in Echtzeit (100+ Formate), Passwort-Wörterbücher und Öko-Modus.",
            ["SupportedFormats"] = "Unterstützte Formate:",
            ["GoToGitHub"] = "GitHub öffnen",
            ["ThemeSelectorTooltip"] = "Design-Thema auswählen",
            ["LanguageSelectorTooltip"] = "Oberflächensprache auswählen",
            ["SingleInstanceTitle"] = "STORM UNARCHIVER",
            ["SingleInstanceMsg"] = "Eine Instanz des Programms läuft bereits und wurde in den Vordergrund gebracht.",
            ["TrayOpen"] = "Hauptfenster öffnen",
            ["TrayToggle"] = "Überwachung",
            ["TrayExit"] = "Beenden",
            ["TrayIdleStatus"] = "STORM UNARCHIVER 1.0.0 — Bereit",
            ["TrayActiveStatus"] = "STORM UNARCHIVER 1.0.0 — Überwachung aktiv"
        },
        ["fr"] = new()
        {
            ["AppTitle"] = "STORM UNARCHIVER 1.0.0",
            ["WatchedFolders"] = "Dossiers surveillés",
            ["PairsCount"] = "{0} paires",
            ["AddPair"] = "Ajouter une paire",
            ["WatchFolderTooltip"] = "Dossier source (surveillance des archives)",
            ["OutputFolderTooltip"] = "Dossier de destination (où extraire)",
            ["BrowseSourceTooltip"] = "Parcourir le dossier source",
            ["BrowseOutputTooltip"] = "Parcourir le dossier de destination",
            ["OpenSourceTooltip"] = "Ouvrir le dossier source dans l'Explorateur",
            ["OpenOutputTooltip"] = "Ouvrir le dossier de destination dans l'Explorateur",
            ["RemovePairTooltip"] = "Supprimer cette paire de dossiers",
            ["DragWatchPrompt"] = "Glissez un dossier ici ou cliquez sur parcourir",
            ["DragOutputPrompt"] = "Glissez le dossier de destination ici",
            ["EmptyPairsTitle"] = "Aucune paire de dossiers ajoutée",
            ["EmptyPairsSubtitle"] = "Cliquez sur 'Ajouter une paire' pour configurer les dossiers.",
            ["EmptyPairsButton"] = "Ajouter une première paire",
            ["StartMonitoring"] = "Démarrer la surveillance",
            ["StopMonitoring"] = "Arrêter la surveillance",
            ["Processed"] = "Extraits",
            ["Errors"] = "Erreurs",
            ["DeleteArchive"] = "Supprimer l'archive",
            ["DeleteArchiveTooltip"] = "Supprimer l'archive source après extraction réussie",
            ["RecursiveUnpack"] = "Imbriquées",
            ["RecursiveUnpackTooltip"] = "Décompression récursive des archives imbriquées",
            ["LowPriority"] = "Mode éco",
            ["LowPriorityTooltip"] = "Mode éco : priorité réduite pour le processeur et le disque",
            ["AutoStart"] = "Démarrage auto",
            ["AutoStartTooltip"] = "Lancer STORM UNARCHIVER au démarrage de Windows",
            ["Subfolders"] = "Sous-dossiers",
            ["SubfoldersTooltip"] = "Surveiller les archives dans tous les sous-dossiers",
            ["PreserveStructure"] = "Structure",
            ["PreserveStructureTooltip"] = "Conserver l'arborescence des dossiers de l'archive",
            ["Notifications"] = "Notifications",
            ["NotificationsTooltip"] = "Afficher les notifications Windows",
            ["FilterPresets"] = "Préréglages de filtres :",
            ["PresetAll"] = "Tous les formats (100+)",
            ["PresetCommon"] = "Courants (ZIP, RAR, 7Z, TAR)",
            ["PresetDiskImages"] = "Images disque (ISO, IMG, VHD)",
            ["PresetReset"] = "Réinitialiser",
            ["OnlyFormats"] = "Seulement",
            ["ExcludeFormats"] = "Exclure",
            ["Password"] = "Mot de passe",
            ["PasswordPlaceholder"] = "pour les archives",
            ["RevealPasswordTooltip"] = "Afficher ou masquer le mot de passe",
            ["PasswordDictTooltip"] = "Gestionnaire de dictionnaires de mots de passe",
            ["PasswordDictTitle"] = "Dictionnaire de mots de passe",
            ["PasswordDictSubtitle"] = "Test séquentiel pour archives chiffrées",
            ["PasswordDictDesc"] = "Entrez les mots de passe (un par ligne) :",
            ["PasswordDictPick"] = "Fichier .txt",
            ["PasswordDictClear"] = "Effacer",
            ["Delay"] = "Délai",
            ["DelaySec"] = "{0} s",
            ["Threads"] = "Fils",
            ["Retries"] = "Essais",
            ["ActivityLog"] = "Journal d'activité",
            ["LogFilterAll"] = "Tous",
            ["LogFilterSuccess"] = "Succès",
            ["LogFilterError"] = "Erreurs",
            ["LogFilterInfo"] = "Info",
            ["LogSearchPlaceholder"] = "Rechercher dans le journal...",
            ["Export"] = "Exporter",
            ["ExportTooltip"] = "Exporter le journal en TXT ou CSV",
            ["ClearLog"] = "Effacer",
            ["ClearLogTooltip"] = "Effacer toutes les entrées du journal",
            ["EmptyLogTitle"] = "Le journal d'activité est vide",
            ["EmptyLogSubtitle"] = "Les événements de surveillance et d'extraction s'afficheront ici.",
            ["StatusReady"] = "Prêt pour la surveillance",
            ["StatusMonitoring"] = "Surveillance active ({0} paires)",
            ["StatusStopped"] = "Surveillance arrêtée",
            ["AboutTooltip"] = "À propos et aide",
            ["AboutDescription"] = "Extraction d'archives en arrière-plan et en temps réel (100+ formats), dictionnaires et mode éco.",
            ["SupportedFormats"] = "Formats pris en charge :",
            ["GoToGitHub"] = "Ouvrir GitHub",
            ["ThemeSelectorTooltip"] = "Choisir le thème visuel",
            ["LanguageSelectorTooltip"] = "Choisir la langue de l'interface",
            ["SingleInstanceTitle"] = "STORM UNARCHIVER",
            ["SingleInstanceMsg"] = "Une instance du programme est déjà en cours d'exécution.",
            ["TrayOpen"] = "Ouvrir la fenêtre principale",
            ["TrayToggle"] = "Surveillance",
            ["TrayExit"] = "Quitter",
            ["TrayIdleStatus"] = "STORM UNARCHIVER 1.0.0 — En attente",
            ["TrayActiveStatus"] = "STORM UNARCHIVER 1.0.0 — Surveillance active"
        },
        ["zh"] = new()
        {
            ["AppTitle"] = "STORM UNARCHIVER 1.0.0",
            ["WatchedFolders"] = "监控文件夹",
            ["PairsCount"] = "{0} 对",
            ["AddPair"] = "添加文件夹对",
            ["WatchFolderTooltip"] = "源文件夹（监控新压缩包）",
            ["OutputFolderTooltip"] = "目标解压文件夹",
            ["BrowseSourceTooltip"] = "在资源管理器中浏览源文件夹",
            ["BrowseOutputTooltip"] = "在资源管理器中浏览目标文件夹",
            ["OpenSourceTooltip"] = "在资源管理器中打开源文件夹",
            ["OpenOutputTooltip"] = "在资源管理器中打开目标文件夹",
            ["RemovePairTooltip"] = "删除此文件夹对",
            ["DragWatchPrompt"] = "将文件夹拖放到此处或点击浏览",
            ["DragOutputPrompt"] = "将目标文件夹拖放到此处",
            ["EmptyPairsTitle"] = "未添加任何文件夹对",
            ["EmptyPairsSubtitle"] = "点击“添加文件夹对”设置监控和解压路径。",
            ["EmptyPairsButton"] = "添加首个文件夹对",
            ["StartMonitoring"] = "开始监控",
            ["StopMonitoring"] = "停止监控",
            ["Processed"] = "已解压",
            ["Errors"] = "错误",
            ["DeleteArchive"] = "删除源压缩包",
            ["DeleteArchiveTooltip"] = "解压成功后自动删除源压缩包",
            ["RecursiveUnpack"] = "嵌套解压",
            ["RecursiveUnpackTooltip"] = "递归解压：自动解压压缩包内的所有嵌套压缩包",
            ["LowPriority"] = "节能模式",
            ["LowPriorityTooltip"] = "节能模式：低 CPU 与磁盘 I/O 优先级",
            ["AutoStart"] = "开机自启",
            ["AutoStartTooltip"] = "随 Windows 自动启动 STORM UNARCHIVER",
            ["Subfolders"] = "包含子文件夹",
            ["SubfoldersTooltip"] = "监控所有子文件夹内的压缩包",
            ["PreserveStructure"] = "保留目录结构",
            ["PreserveStructureTooltip"] = "保持压缩包内部的目录层级",
            ["Notifications"] = "系统通知",
            ["NotificationsTooltip"] = "显示 Windows 气泡通知",
            ["FilterPresets"] = "格式预设：",
            ["PresetAll"] = "所有格式 (100+)",
            ["PresetCommon"] = "常用格式 (ZIP, RAR, 7Z, TAR)",
            ["PresetDiskImages"] = "光盘镜像 (ISO, IMG, VHD)",
            ["PresetReset"] = "重置",
            ["OnlyFormats"] = "仅限格式",
            ["ExcludeFormats"] = "排除格式",
            ["Password"] = "密码",
            ["PasswordPlaceholder"] = "解压密码",
            ["RevealPasswordTooltip"] = "显示或隐藏密码",
            ["PasswordDictTooltip"] = "密码字典管理器（自动尝试列表）",
            ["PasswordDictTitle"] = "密码字典",
            ["PasswordDictSubtitle"] = "加密压缩包自动按序尝试",
            ["PasswordDictDesc"] = "输入密码列表（每行一个）：",
            ["PasswordDictPick"] = "选择 .txt 文件",
            ["PasswordDictClear"] = "清空",
            ["Delay"] = "延迟",
            ["DelaySec"] = "{0} 秒",
            ["Threads"] = "线程数",
            ["Retries"] = "重试次数",
            ["ActivityLog"] = "运行日志",
            ["LogFilterAll"] = "全部",
            ["LogFilterSuccess"] = "成功",
            ["LogFilterError"] = "错误",
            ["LogFilterInfo"] = "信息",
            ["LogSearchPlaceholder"] = "在日志中搜索...",
            ["Export"] = "导出",
            ["ExportTooltip"] = "导出日志为 TXT 或 CSV",
            ["ClearLog"] = "清空",
            ["ClearLogTooltip"] = "清空所有日志记录",
            ["EmptyLogTitle"] = "运行日志为空",
            ["EmptyLogSubtitle"] = "监控和解压事件将在此实时显示。",
            ["StatusReady"] = "就绪",
            ["StatusMonitoring"] = "监控中 ({0} 对文件夹)",
            ["StatusStopped"] = "监控已停止",
            ["AboutTooltip"] = "关于与帮助",
            ["AboutDescription"] = "全自动实时后台解压工具（支持 100+ 格式），支持密码字典、递归解压与节能模式。",
            ["SupportedFormats"] = "支持格式：",
            ["GoToGitHub"] = "访问 GitHub",
            ["ThemeSelectorTooltip"] = "选择界面主题",
            ["LanguageSelectorTooltip"] = "选择界面语言",
            ["SingleInstanceTitle"] = "STORM UNARCHIVER",
            ["SingleInstanceMsg"] = "程序实例已在运行中，已为您切换至前台窗口。",
            ["TrayOpen"] = "打开主窗口",
            ["TrayToggle"] = "监控开关",
            ["TrayExit"] = "退出",
            ["TrayIdleStatus"] = "STORM UNARCHIVER 1.0.0 — 等待中",
            ["TrayActiveStatus"] = "STORM UNARCHIVER 1.0.0 — 监控中"
        },
        ["ja"] = new()
        {
            ["AppTitle"] = "STORM UNARCHIVER 1.0.0",
            ["WatchedFolders"] = "監視フォルダー",
            ["PairsCount"] = "{0} ペア",
            ["AddPair"] = "ペアを追加",
            ["WatchFolderTooltip"] = "監視元フォルダー（アーカイブの自動検出）",
            ["OutputFolderTooltip"] = "展開先フォルダー",
            ["BrowseSourceTooltip"] = "エクスプローラーで監視元フォルダーを選択",
            ["BrowseOutputTooltip"] = "エクスプローラーで展開先フォルダーを選択",
            ["OpenSourceTooltip"] = "エクスプローラーで監視元フォルダーを開く",
            ["OpenOutputTooltip"] = "エクスプローラーで展開先フォルダーを開く",
            ["RemovePairTooltip"] = "このフォルダーペアを削除",
            ["DragWatchPrompt"] = "ここにフォルダーをドラッグまたは選択をクリック",
            ["DragOutputPrompt"] = "ここに展開先フォルダーをドラッグ",
            ["EmptyPairsTitle"] = "フォルダーペアが登録されていません",
            ["EmptyPairsSubtitle"] = "「ペアを追加」をクリックして監視元と展開先を設定してください。",
            ["EmptyPairsButton"] = "最初のペアを追加",
            ["StartMonitoring"] = "監視を開始",
            ["StopMonitoring"] = "監視を停止",
            ["Processed"] = "展開済み",
            ["Errors"] = "エラー",
            ["DeleteArchive"] = "アーカイブを削除",
            ["DeleteArchiveTooltip"] = "展開成功後に元のアーカイブを自動削除",
            ["RecursiveUnpack"] = "ネスト展開",
            ["RecursiveUnpackTooltip"] = "再帰的展開：アーカイブ内の入れ子アーカイブを自動展開",
            ["LowPriority"] = "エコモード",
            ["LowPriorityTooltip"] = "エコモード：CPUおよびディスクI/Oの負荷を軽減",
            ["AutoStart"] = "自動起動",
            ["AutoStartTooltip"] = "Windows起動時にSTORM UNARCHIVERを開始",
            ["Subfolders"] = "サブフォルダー",
            ["SubfoldersTooltip"] = "すべてのサブフォルダー内のアーカイブを監視",
            ["PreserveStructure"] = "フォルダー構造",
            ["PreserveStructureTooltip"] = "アーカイブ内のディレクトリ階層を維持",
            ["Notifications"] = "通知",
            ["NotificationsTooltip"] = "Windows通知を表示",
            ["FilterPresets"] = "フィルタープリセット:",
            ["PresetAll"] = "すべての形式 (100+)",
            ["PresetCommon"] = "標準 (ZIP, RAR, 7Z, TAR)",
            ["PresetDiskImages"] = "ディスクイメージ (ISO, IMG, VHD)",
            ["PresetReset"] = "リセット",
            ["OnlyFormats"] = "対象形式",
            ["ExcludeFormats"] = "除外形式",
            ["Password"] = "パスワード",
            ["PasswordPlaceholder"] = "アーカイブ用",
            ["RevealPasswordTooltip"] = "パスワードの表示/非表示",
            ["PasswordDictTooltip"] = "パスワード辞書マネージャー（自動総当たり）",
            ["PasswordDictTitle"] = "パスワード辞書",
            ["PasswordDictSubtitle"] = "暗号化アーカイブの自動順次試行",
            ["PasswordDictDesc"] = "パスワードを1行に1つずつ入力してください：",
            ["PasswordDictPick"] = ".txt ファイルを選択",
            ["PasswordDictClear"] = "クリア",
            ["Delay"] = "遅延",
            ["DelaySec"] = "{0} 秒",
            ["Threads"] = "スレッド",
            ["Retries"] = "リトライ",
            ["ActivityLog"] = "アクティビティログ",
            ["LogFilterAll"] = "すべて",
            ["LogFilterSuccess"] = "成功",
            ["LogFilterError"] = "エラー",
            ["LogFilterInfo"] = "情報",
            ["LogSearchPlaceholder"] = "ログ内を検索...",
            ["Export"] = "エクスポート",
            ["ExportTooltip"] = "ログをTXTまたはCSVファイルに出力",
            ["ClearLog"] = "クリア",
            ["ClearLogTooltip"] = "すべてのログを消去",
            ["EmptyLogTitle"] = "ログは空です",
            ["EmptyLogSubtitle"] = "監視および展開イベントがリアルタイムでここに表示されます。",
            ["StatusReady"] = "監視準備完了",
            ["StatusMonitoring"] = "監視中 ({0} ペア)",
            ["StatusStopped"] = "監視停止中",
            ["AboutTooltip"] = "バージョン情報とヘルプ",
            ["AboutDescription"] = "リアルタイム自動バックグラウンド展開ツール（100+形式対応）。パスワード辞書、再帰展開、エコモード搭載。",
            ["SupportedFormats"] = "対応フォーマット:",
            ["GoToGitHub"] = "GitHubを開く",
            ["ThemeSelectorTooltip"] = "テーマを選択",
            ["LanguageSelectorTooltip"] = "表示言語を選択",
            ["SingleInstanceTitle"] = "STORM UNARCHIVER",
            ["SingleInstanceMsg"] = "プログラムは既に起動しており、最前面に表示されました。",
            ["TrayOpen"] = "メインウィンドウを開く",
            ["TrayToggle"] = "監視切り替え",
            ["TrayExit"] = "終了",
            ["TrayIdleStatus"] = "STORM UNARCHIVER 1.0.0 — 待機中",
            ["TrayActiveStatus"] = "STORM UNARCHIVER 1.0.0 — 監視中"
        }
    };

    private LocalizationManager()
    {
    }

    public void SetLanguage(string langCode)
    {
        if (!_strings.ContainsKey(langCode)) langCode = "ru";
        CurrentLanguage = langCode;
        LanguageChanged?.Invoke(this, EventArgs.Empty);
    }

    public string GetString(string key, params object[] args)
    {
        if (_strings.TryGetValue(CurrentLanguage, out var dict) && dict.TryGetValue(key, out var val))
        {
            return args.Length > 0 ? string.Format(val, args) : val;
        }

        // Fallback to Russian
        if (_strings.TryGetValue("ru", out var ruDict) && ruDict.TryGetValue(key, out var ruVal))
        {
            return args.Length > 0 ? string.Format(ruVal, args) : ruVal;
        }

        return key;
    }
}
